### ISSUE TITLE
大佬能不能让这个插件运行起来，插件列表看得到，但是用不了

### ISSUE THREAD

**Issue by duoshoumiao** [RSRH-Rs/whoatme#2]
from hoshino import Service, priv
from random import sample

sv = Service('抽奖', visible=False, enable_on_default=False)

participants = []  # 参与者列表

@sv.on_command('set_lottery', aliases=('设置抽奖',))
async def set_lottery(bot, ev):
    args = ev.message.extract_plain_text().split()  # 提取参数

    if len(args) != 2:  # 参数个数错误
        await bot.send(ev, '参数错误，请按照格式输入参与人数和奖项数目（示例：设置抽奖 10 3）')
        return

    try:
        participant_count = int(args[0])  # 参与人数
        prize_count = int(args[1])  # 奖项数目
    except ValueError:
        await bot.send(ev, '参数错误，请输入有效的数字')
        return

    # 在这里编写设置参与人数和奖项的逻辑
    # 例如，您可以将参与人数和奖项数保存到数据库中，以便后续使用

    await bot.send(ev, f'抽奖设置成功！参与人数：{participant_count}，奖项数目：{prize_count}')

@sv.on_command('start_lottery', aliases=('开始抽奖',))
async def start_lottery(bot, ev):
    # 在这里编写开始抽奖的逻辑
    # 例如，您可以从数据库中获取参与人数和奖项数，然后进行抽奖操作

    await bot.send(ev, '抽奖已经开始！')

    # 编写抽奖逻辑并生成中奖名单
    winners = sample(participants, prize_count)

    await bot.send(ev,  f'抽奖已经完成！中奖名单：{", ".join(winners)}')

@sv.on_command('join_lottery', aliases=('参与抽奖',))
async def join_lottery(bot, ev):
    if ev.group_id:  # 在群里
        if ev.user_id not in participants:
            participants.append(ev.user_id)
            await bot.send(ev, '参与成功！')
        else:
            await bot.send(ev, '您已经参与过抽奖了！')
    else:
        await bot.send(ev, '此命令只能在群里使用！', at_sender=True)

@sv.on_command('participants', aliases=('参与者',))
@priv.check_privilege(priv.SUPERUSER)
async def list_participants(bot, ev):
    # 显示当前的参与者列表
    participant_list = ', '.join(str(p) for p in participants)
    await bot.send(ev, f'当前参与者：{participant_list}')

**Comment by RSRH-Rs** [comment]
报错信息呢 想要的结果是什么

**Comment by duoshoumiao** [comment]
> 报错信息呢 想要的结果是什么

弄好了
