### ISSUE TITLE
LLO用不了 怎么办

### ISSUE THREAD

**Issue by duoshoumiao** [RSRH-Rs/whoatme#5]
![5a0151b5b29065ab5a012e62305f60b2](https://github.com/user-attachments/assets/c3fa68c5-7478-4a7d-aa7c-1aa3ac1b7f26)

**Comment by RSRH-Rs** [comment]
后台有报错信息吗 把 `@莱宝` 那一条后台信息截图给我看看

**Comment by duoshoumiao** [comment]
![image](https://github.com/user-attachments/assets/6cef8094-f895-4a6d-abc4-441d0ff9a06d)
没有报错

**Comment by RSRH-Rs** [comment]
我要 @人的那一条

**Comment by duoshoumiao** [comment]
![image](https://github.com/user-attachments/assets/f18f8bea-a7fc-462c-b266-8586457a222c)

**Comment by duoshoumiao** [comment]
![1147020c2bb123ef92c52db344aeddaf](https://github.com/user-attachments/assets/966f9153-8451-4d68-a47d-e05e835e6f22)

**Comment by RSRH-Rs** [comment]
更新了，后台输出好像更新了和旧版不一样 换了下正则匹配规则 你再试试

**Comment by duoshoumiao** [comment]
好的 谢谢大佬

**Comment by duoshoumiao** [comment]
![image](https://github.com/user-attachments/assets/b57c57a5-5c3f-4164-a8bb-9b1617d3c62f)
可以了
